version: '3.3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    expose:
        - '27017'
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'movie-dev'
      MYSQL_USER: 'usr-movie'
      MYSQL_PASSWORD: 'pwd-movie'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3366:3306'
    expose:
      - '3306'
  zipkin:
    image: openzipkin/zipkin:2
    container_name: zipkin
    restart: always
    ports:
      - '9411:9411'
    expose:
      - '9411'
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'  # RabbitMQ Dashboard
    expose:
      - '5672'
      - '15672'

